# Exploratory Data Analysis

Understanding the dataset to explore how the data is present in the database and if there is a need of creating some aggregated tables that can help with
        * Vendor selection for profitability 
        * Product Pricing Optimizatio

In [3]:
import pandas as pd
from sqlalchemy import create_engine

In [51]:
engine = create_engine('mysql+pymysql://root:<paasword>@localhost:3306/inventorydb')

In [5]:
df = pd.read_sql("show tables",engine)

In [7]:
df

  Tables_in_inventorydb
0       begin_inventory
1         end_inventory
2       purchase_prices
3             purchases
4                 sales
5        vendor_invoice

In [9]:
tables = pd.read_sql("SHOW TABLES", engine)
print(tables)

  Tables_in_inventorydb
0       begin_inventory
1         end_inventory
2       purchase_prices
3             purchases
4                 sales
5        vendor_invoice

In [10]:
for table in tables['Tables_in_inventorydb']:
    print('-'*25, table, '-'*25)
    print('Count of records:', pd.read_sql(f"select count(*) as count from {table}", engine)['count'].values[0])
    display(pd.read_sql(f"select * from {table} limit 5",engine))

------------------------- begin_inventory -------------------------
Count of records: 206529

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,startDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,8,12.99,2024-01-01
1,1_HARDERSFIELD_60,1,HARDERSFIELD,60,Canadian Club 1858 VAP,750mL,7,10.99,2024-01-01
2,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,6,36.99,2024-01-01
3,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,3,38.99,2024-01-01
4,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,6,34.99,2024-01-01

------------------------- end_inventory -------------------------
Count of records: 224489

,InventoryId,Store,City,Brand,Description,Size,onHand,Price,endDate
0,1_HARDERSFIELD_58,1,HARDERSFIELD,58,Gekkeikan Black & Gold Sake,750mL,11,12.99,2024-12-31
1,1_HARDERSFIELD_62,1,HARDERSFIELD,62,Herradura Silver Tequila,750mL,7,36.99,2024-12-31
2,1_HARDERSFIELD_63,1,HARDERSFIELD,63,Herradura Reposado Tequila,750mL,7,38.99,2024-12-31
3,1_HARDERSFIELD_72,1,HARDERSFIELD,72,No. 3 London Dry Gin,750mL,4,34.99,2024-12-31
4,1_HARDERSFIELD_75,1,HARDERSFIELD,75,Three Olives Tomato Vodka,750mL,7,14.99,2024-12-31

------------------------- purchase_prices -------------------------
Count of records: 12261

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,58,Gekkeikan Black & Gold Sake,12.99,750mL,750,1,9.28,8320,SHAW ROSS INT L IMP LTD
1,62,Herradura Silver Tequila,36.99,750mL,750,1,28.67,1128,BROWN-FORMAN CORP
2,63,Herradura Reposado Tequila,38.99,750mL,750,1,30.46,1128,BROWN-FORMAN CORP
3,72,No. 3 London Dry Gin,34.99,750mL,750,1,26.11,9165,ULTRA BEVERAGE COMPANY LLP
4,75,Three Olives Tomato Vodka,14.99,750mL,750,1,10.94,7245,PROXIMO SPIRITS INC.

------------------------- purchases -------------------------
Count of records: 2372474

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,69_MOUNTMEND_8412,69,8412,Tequila Ocho Plata Fresno,750mL,105,ALTAMAR BRANDS LLC,8124,2023-12-21,2024-01-02,2024-01-04,2024-02-16,35.71,6,214.26,1
1,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
2,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
3,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
4,76_DONCASTER_2034,76,2034,Glendalough Double Barrel,750mL,388,ATLANTIC IMPORTING COMPANY,8169,2023-12-24,2024-01-02,2024-01-09,2024-02-16,21.32,5,106.60,1

------------------------- sales -------------------------
Count of records: 6186000

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

------------------------- vendor_invoice -------------------------
Count of records: 5543

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,105,ALTAMAR BRANDS LLC,2024-01-04,8124,2023-12-21,2024-02-16,6,214.26,3.47,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
2,388,ATLANTIC IMPORTING COMPANY,2024-01-09,8169,2023-12-24,2024-02-16,5,106.60,4.61,None
3,480,BACARDI USA INC,2024-01-12,8106,2023-12-20,2024-02-05,10100,137483.78,2935.20,None
4,516,BANFI PRODUCTS CORP,2024-01-07,8170,2023-12-24,2024-02-12,1935,15527.25,429.20,None

In [11]:
purchases = pd.read_sql("select * from purchases where VendorNumber = 4466",engine)
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [12]:
purchases_price = pd.read_sql("select * from purchase_prices where VendorNumber = 4466",engine)
purchases_price

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [13]:
purchases.groupby(['Brand','PurchasePrice'])[['Quantity','Dollars']].sum()

                     Quantity   Dollars
Brand PurchasePrice
3140  11.19              4640  51921.60
5215  9.41               4923  46325.43
5255  9.35               6215  58110.25

In [14]:
purchases_price

,Brand,Description,Price,Size,Volume,Classification,PurchasePrice,VendorNumber,VendorName
0,5215,TGI Fridays Long Island Iced,12.99,1750mL,1750,1,9.41,4466,AMERICAN VINTAGE BEVERAGE
1,5255,TGI Fridays Ultimte Mudslide,12.99,1750mL,1750,1,9.35,4466,AMERICAN VINTAGE BEVERAGE
2,3140,TGI Fridays Orange Dream,14.99,1750mL,1750,1,11.19,4466,AMERICAN VINTAGE BEVERAGE

In [15]:
invoice = pd.read_sql("select * from vendor_invoice where VendorNumber = 4466",engine)
invoice

,VendorNumber,VendorName,InvoiceDate,PONumber,PODate,PayDate,Quantity,Dollars,Freight,Approval
0,4466,AMERICAN VINTAGE BEVERAGE,2024-01-07,8137,2023-12-22,2024-02-21,15,140.55,8.57,None
1,4466,AMERICAN VINTAGE BEVERAGE,2024-01-19,8207,2023-12-27,2024-02-26,335,3142.33,16.97,None
2,4466,AMERICAN VINTAGE BEVERAGE,2024-01-18,8307,2024-01-03,2024-02-18,41,383.35,1.99,None
3,4466,AMERICAN VINTAGE BEVERAGE,2024-01-27,8469,2024-01-14,2024-03-11,72,673.20,3.30,None
4,4466,AMERICAN VINTAGE BEVERAGE,2024-02-04,8532,2024-01-19,2024-03-15,79,740.21,3.48,None
5,4466,AMERICAN VINTAGE BEVERAGE,2024-02-09,8604,2024-01-24,2024-03-15,347,3261.37,17.61,None
6,4466,AMERICAN VINTAGE BEVERAGE,2024-02-17,8793,2024-02-05,2024-04-02,72,675.36,3.17,None
7,4466,AMERICAN VINTAGE BEVERAGE,2024-03-01,8892,2024-02-12,2024-03-28,117,1096.05,5.15,None
8,4466,AMERICAN VINTAGE BEVERAGE,2024-03-07,8995,2024-02-19,2024-04-02,129,1209.27,5.44,None
9,4466,AMERICAN VINTAGE BEVERAGE,2024-03-12,9033,2024-02-22,2024-04-16,147,1377.87,6.61,None
10,4466,AMERICAN VINTAGE BEVERAGE,2024-03-16,9180,2024-03-03,2024-04-19,211,1979.33,9.50,None
11,4466,AMERICAN VINTAGE BEVERAGE,2024-03-23,9244,2024-03-08,2024-04-21,161,1510.69,6.95,None
12,4466,AMERICAN VINTAGE BEVERAGE,2024-03-31,9371,2024-03-17,2024-05-13,176,1649.20,8.91,None
13,4466,AMERICAN VINTAGE BEVERAGE,2024-04-09,9491,2024-03-24,2024-05-08,215,2016.43,10.08,None
14,4466,AMERICAN VINTAGE BEVERAGE,2024-04-17,9583,2024-03-31,2024-05-12,110,1035.10,5.69,None
15,4466,AMERICAN VINTAGE BEVERAGE,2024-04-20,9639,2024-04-04,2024-06-04,515,5323.01,25.02,None
16,4466,AMERICAN VINTAGE BEVERAGE,2024-04-29,9800,2024-04-15,2024-06-07,275,2775.01,13.60,None
17,4466,AMERICAN VINTAGE BEVERAGE,2024-05-09,9886,2024-04-21,2024-06-12,312,3050.86,13.73,None
18,4466,AMERICAN VINTAGE BEVERAGE,2024-05-14,9999,2024-04-29,2024-06-26,310,3117.82,14.97,None
19,4466,AMERICAN VINTAGE BEVERAGE,2024-05-16,10095,2024-05-06,2024-06-27,215,2123.01,11.46,None
20,4466,AMERICAN VINTAGE BEVERAGE,2024-05-28,10169,2024-05-11,2024-07-04,327,3298.55,15.83,None
21,4466,AMERICAN VINTAGE BEVERAGE,2024-06-04,10257,2024-05-17,2024-07-08,376,3708.18,20.39,None
22,4466,AMERICAN VINTAGE BEVERAGE,2024-06-12,10346,2024-05-23,2024-07-20,640,6458.38,29.71,None
23,4466,AMERICAN VINTAGE BEVERAGE,2024-06-17,10445,2024-05-30,2024-07-19,288,2937.56,15.86,None
24,4466,AMERICAN VINTAGE BEVERAGE,2024-06-22,10600,2024-06-09,2024-08-01,308,3213.28,17.03,None
25,4466,AMERICAN VINTAGE BEVERAGE,2024-06-29,10695,2024-06-16,2024-08-12,143,1585.75,8.09,None
26,4466,AMERICAN VINTAGE BEVERAGE,2024-07-09,10777,2024-06-22,2024-08-15,18,179.88,0.99,None
27,4466,AMERICAN VINTAGE BEVERAGE,2024-07-08,10836,2024-06-25,2024-08-14,8,85.96,0.43,None
28,4466,AMERICAN VINTAGE BEVERAGE,2024-07-11,10969,2024-06-29,2024-08-18,94,993.12,5.06,None
29,4466,AMERICAN VINTAGE BEVERAGE,2024-07-19,11085,2024-07-06,2024-09-04,601,5883.09,31.18,None
30,4466,AMERICAN VINTAGE BEVERAGE,2024-07-26,11187,2024-07-14,2024-08-26,1535,15406.69,77.03,None
31,4466,AMERICAN VINTAGE BEVERAGE,2024-08-03,11244,2024-07-18,2024-09-04,266,2888.22,15.31,None
32,4466,AMERICAN VINTAGE BEVERAGE,2024-08-11,11362,2024-07-26,2024-09-24,206,2171.64,11.08,None
33,4466,AMERICAN VINTAGE BEVERAGE,2024-08-18,11489,2024-08-04,2024-09-16,768,7292.98,37.92,None
34,4466,AMERICAN VINTAGE BEVERAGE,2024-08-24,11540,2024-08-08,2024-10-02,1207,12242.43,64.88,None
35,4466,AMERICAN VINTAGE BEVERAGE,2024-09-02,11716,2024-08-19,2024-09-29,433,4334.43,20.37,None
36,4466,AMERICAN VINTAGE BEVERAGE,2024-09-12,11771,2024-08-23,2024-10-11,370,3640.18,18.20,None
37,4466,AMERICAN VINTAGE BEVERAGE,2024-09-20,11901,2024-09-01,2024-10-30,358,3626.74,16.32,None
38,4466,AMERICAN VINTAGE BEVERAGE,2024-09-25,11993,2024-09-07,2024-10-23,233,2264.85,12.23,None
39,4466,AMERICAN VINTAGE BEVERAGE,2024-10-01,12125,2024-09-16,2024-11-07,284,2813.46,15.47,None
40,4466,AMERICAN VINTAGE BEVERAGE,2024-10-08,12235,2024-09-23,2024-11-20,258,2592.08,11.92,None
41,4466,AMERICAN VINTAGE BEVERAGE,2024-10-09,12253,2024-09-23,2024-11-14,1,11.19,0.05,None
42,4466,AMERICAN VINTAGE BEVERAGE,2024-10-12,12321,2024-09-26,2024-11-19,172,1685.98,7.59,None
43,4466,AMERICAN VINTAGE BEVERAGE,2024-10-20,12466,2024-10-05,2024-11-26,280,2798.60,14.55,None
44,4466,AMERICAN VINTAGE BEVERAGE,2024-10-27,12515,2024-10-09,2024-11-30,178,1763.28,8.64,None
45,4466,AMERICAN VINTAGE BEVERAGE,2024-11-07,12702,2024-10-21,2024-12-11,183,1812.77,8.70,None
46,4466,AMERICAN VINTAGE BEVERAGE,2024-11-12,12752,2024-10-25,2024-12-11,216,2156.16,10.57,None
47,4466,AMERICAN VINTAGE BEVERAGE,2024-11-20,12828,2024-10-30,2024-12-18,262,2597.36,12.99,None
48,4466,AMERICAN VINTAGE BEVERAGE,2024-11-27,12929,2024-11-06,2025-01-04,270,2622.32,12.85,None
49,4466,AMERICAN VINTAGE BEVERAGE,2024-11-28,13092,2024-11-16,2024-12-30,209,2036.17,11.20,None
50,4466,AMERICAN VINTAGE BEVERAGE,2024-12-06,13134,2024-11-20,2025-01-18,305,3018.89,15.70,None
51,4466,AMERICAN VINTAGE BEVERAGE,2024-12-16,13254,2024-11-28,2025-01-13,262,2530.36,11.39,None
52,4466,AMERICAN VINTAGE BEVERAGE,2024-12-26,13432,2024-12-09,2025-01-27,231,2263.43,11.32,None
53,4466,AMERICAN VINTAGE BEVERAGE,2024-12-30,13483,2024-12-13,2025-02-11,221,2178.27,11.33,None
54,4466,AMERICAN VINTAGE BEVERAGE,2025-01-09,13627,2024-12-22,2025-02-05,413,3985.03,19.53,None

In [16]:
purchases

,InventoryId,Store,Brand,Description,Size,VendorNumber,VendorName,PONumber,PODate,ReceivingDate,InvoiceDate,PayDate,PurchasePrice,Quantity,Dollars,Classification
0,30_CULCHETH_5255,30,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,4,37.40,1
1,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-02,2024-01-07,2024-02-21,9.41,5,47.05,1
2,1_HARDERSFIELD_5255,1,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8137,2023-12-22,2024-01-01,2024-01-07,2024-02-21,9.35,6,56.10,1
3,38_GOULCREST_5215,38,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-07,2024-01-19,2024-02-26,9.41,6,56.46,1
4,59_CLAETHORPES_5215,59,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,8207,2023-12-27,2024-01-05,2024-01-19,2024-02-26,9.41,6,56.46,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2187,81_PEMBROKE_5215,81,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-29,2025-01-04,2025-02-10,9.41,6,56.46,1
2188,62_KILMARNOCK_5255,62,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.35,5,46.75,1
2189,34_PITMERDEN_5215,34,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-28,2025-01-04,2025-02-10,9.41,5,47.05,1
2190,6_GOULCREST_5215,6,5215,TGI Fridays Long Island Iced,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-31,2025-01-04,2025-02-10,9.41,6,56.46,1
2191,35_HALIVAARA_5255,35,5255,TGI Fridays Ultimte Mudslide,1.75L,4466,AMERICAN VINTAGE BEVERAGE,13595,2024-12-20,2024-12-27,2025-01-04,2025-02-10,9.35,5,46.75,1

In [15]:
invoice['PONumber'].nunique()

55

In [17]:
invoice.shape

(55, 10)

In [24]:
purchases.columns

<bound method DataFrame.count of               InventoryId  Store  Brand                   Description   Size  \
0        30_CULCHETH_5255     30   5255  TGI Fridays Ultimte Mudslide  1.75L
1       34_PITMERDEN_5215     34   5215  TGI Fridays Long Island Iced  1.75L
2     1_HARDERSFIELD_5255      1   5255  TGI Fridays Ultimte Mudslide  1.75L
3       38_GOULCREST_5215     38   5215  TGI Fridays Long Island Iced  1.75L
4     59_CLAETHORPES_5215     59   5215  TGI Fridays Long Island Iced  1.75L
...                   ...    ...    ...                           ...    ...
2187     81_PEMBROKE_5215     81   5215  TGI Fridays Long Island Iced  1.75L
2188   62_KILMARNOCK_5255     62   5255  TGI Fridays Ultimte Mudslide  1.75L
2189    34_PITMERDEN_5215     34   5215  TGI Fridays Long Island Iced  1.75L
2190     6_GOULCREST_5215      6   5215  TGI Fridays Long Island Iced  1.75L
2191    35_HALIVAARA_5255     35   5255  TGI Fridays Ultimte Mudslide  1.75L

      VendorNumber                   VendorName  PONumber      PODate  \
0             4466  AMERICAN VINTAGE BEVERAGE        8137  2023-12-22
1             4466  AMERICAN VINTAGE BEVERAGE        8137  2023-12-22
2             4466  AMERICAN VINTAGE BEVERAGE        8137  2023-12-22
3             4466  AMERICAN VINTAGE BEVERAGE        8207  2023-12-27
4             4466  AMERICAN VINTAGE BEVERAGE        8207  2023-12-27
...            ...                          ...       ...         ...
2187          4466  AMERICAN VINTAGE BEVERAGE       13595  2024-12-20
2188          4466  AMERICAN VINTAGE BEVERAGE       13595  2024-12-20
2189          4466  AMERICAN VINTAGE BEVERAGE       13595  2024-12-20
2190          4466  AMERICAN VINTAGE BEVERAGE       13595  2024-12-20
2191          4466  AMERICAN VINTAGE BEVERAGE       13595  2024-12-20

     ReceivingDate InvoiceDate     PayDate  PurchasePrice  Quantity  Dollars  \
0       2024-01-01  2024-01-07  2024-02-21           9.35         4    37.40
1       2024-01-02  2024-01-07  2024-02-21           9.41         5    47.05
2       2024-01-01  2024-01-07  2024-02-21           9.35         6    56.10
3       2024-01-07  2024-01-19  2024-02-26           9.41         6    56.46
4       2024-01-05  2024-01-19  2024-02-26           9.41         6    56.46
...            ...         ...         ...            ...       ...      ...
2187    2024-12-29  2025-01-04  2025-02-10           9.41         6    56.46
2188    2024-12-28  2025-01-04  2025-02-10           9.35         5    46.75
2189    2024-12-28  2025-01-04  2025-02-10           9.41         5    47.05
2190    2024-12-31  2025-01-04  2025-02-10           9.41         6    56.46
2191    2024-12-27  2025-01-04  2025-02-10           9.35         5    46.75

      Classification
0                  1
1                  1
2                  1
3                  1
4                  1
...              ...
2187               1
2188               1
2189               1
2190               1
2191               1

[2192 rows x 16 columns]>

In [28]:
inv = invoice.columns

In [31]:
pp = purchases_price.columns

In [29]:
df = purchases.columns

In [35]:
len(df)

16

In [33]:
len(pp)

9

In [34]:
len(inv)

10

In [26]:
sales = pd.read_sql("select * from sales limit 5",engine)
sales

,InventoryId,Store,Brand,Description,Size,SalesQuantity,SalesDollars,SalesPrice,SalesDate,Volume,Classification,ExciseTax,VendorNo,VendorName
0,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-01,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
1,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,2,32.98,16.49,2024-01-02,750.0,1,1.57,12546,JIM BEAM BRANDS COMPANY
2,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,16.49,16.49,2024-01-03,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
3,1_HARDERSFIELD_1004,1,1004,Jim Beam w/2 Rocks Glasses,750mL,1,14.49,14.49,2024-01-08,750.0,1,0.79,12546,JIM BEAM BRANDS COMPANY
4,1_HARDERSFIELD_1005,1,1005,Maker's Mark Combo Pack,375mL 2 Pk,2,69.98,34.99,2024-01-09,375.0,1,0.79,12546,JIM BEAM BRANDS COMPANY

In [27]:
sales.groupby(['Brand'])[['SalesPrice', 'SalesQuantity']].sum()

       SalesPrice  SalesQuantity
Brand
1004        63.96              5
1005        34.99              2

* The purchases table contains actual purchases data, including the date of purchases, products (brands) purchased by vendors, the amount paid (in dollars),
* The purchases prices column is derived from the purchase_prices table, which provide product-wise actual and purchase prices. The combination of vendor and brand is unique in the table.
* the vendor_invoice table aggregates data from the purchase table, summarising quantity and dollar amounts, along with an additional column for freight. This table maintains uniqueness based on vendor and PO number.
* The sales table capture actual sales transactions, detailing and brands purchased by vendors, the quantity sold, the selling price, and the revenue warned.

As the data that we need for analysis is distributed in diffrent tables, we need to create a summary table containing:
 * purchase transaction made by vendors.
 * sales transaction data.
 * freight costs for each vendor.
 * actual product prices from vendors.

In [12]:
freight_summary = pd.read_sql("select VendorNumber, SUM(Freight) as FreightCost from vendor_invoice group by VendorNumber", engine)

In [13]:
freight_summary

     VendorNumber  FreightCost
0             105        62.39
1            4466       793.91
2             388       211.74
3             480     89286.27
4             516      8510.41
..            ...          ...
121        201359         0.09
122          4901         0.72
123         90059        74.84
124          5083        10.68
125            54         0.48

[126 rows x 2 columns]

In [17]:
pd.read_sql("""
SELECT 
    p.VendorNumber,  
    p.VendorName,  
    p.Brand,  
    p.PurchasePrice, 
    pp.Volume,
    pp.Price AS ActualPrice,
    SUM(p.Quantity) AS TotalPurchaseQuantity, 
    SUM(p.Dollars) AS TotalPurchaseDollars 
FROM purchases p 
JOIN purchase_prices pp 
    ON p.Brand = pp.Brand 
    WHERE p.PurchasePrice > 0
GROUP BY 
    p.VendorNumber, 
    p.VendorName, 
    p.Brand,
    p.PurchasePrice,
    pp.Volume,
    pp.Price
ORDER BY 
    TotalPurchaseDollars
""", engine)

,VendorNumber,VendorName,Brand,PurchasePrice,Volume,ActualPrice,TotalPurchaseQuantity,TotalPurchaseDollars
0,7245,PROXIMO SPIRITS INC.,3065,0.71,50,0.99,1.0,0.71
1,3960,DIAGEO NORTH AMERICA INC,6127,1.47,200,1.99,1.0,1.47
2,3924,HEAVEN HILL DISTILLERIES,9123,0.74,50,0.99,2.0,1.48
3,8004,SAZERAC CO INC,5683,0.39,50,0.49,6.0,2.34
4,9815,WINE GROUP INC,8527,1.32,750,4.99,2.0,2.64
...,...,...,...,...,...,...,...,...
10687,3960,DIAGEO NORTH AMERICA INC,3545,21.89,1750,29.99,138109.0,3023206.01
10688,3960,DIAGEO NORTH AMERICA INC,4261,16.17,1750,22.99,201682.0,3261197.94
10689,17035,PERNOD RICARD USA,8068,18.24,1750,24.99,187407.0,3418303.68
10690,4425,MARTIGNETTI COMPANIES,3405,23.19,1750,28.99,164038.0,3804041.22
10691,1128,BROWN-FORMAN CORP,1233,26.27,1750,36.99,145080.0,3811251.60

In [31]:
pd.read_sql("""
SELECT 
    VendorNo,
    Brand,
    SUM(SalesDollars) as TotalSalesDollars,
    SUM(SalesPrice) as TotalSalesPrice,
    SUM(SalesQuantity) as TotalSalesQuantity,
    SUM(ExciseTax) as TotalExciseTax
FROM sales
GROUP BY VendorNo, Brand
ORDER BY TotalSalesDollars
""", engine)

,VendorNo,Brand,TotalSalesDollars,TotalSalesPrice,TotalSalesQuantity,TotalExciseTax
0,8004,5287,0.98,0.98,2.0,0.10
1,9206,2773,0.99,0.99,1.0,0.05
2,3252,3933,1.98,0.99,2.0,0.10
3,10050,3623,1.98,1.98,2.0,0.10
4,660,2134,2.49,2.49,1.0,0.39
...,...,...,...,...,...,...
9392,3960,3545,1722112.36,258113.09,54964.0,100989.62
9393,4425,3405,1734093.61,267241.03,57235.0,105162.40
9394,17035,8068,1803317.48,224227.09,72702.0,133582.25
9395,1128,1233,1983632.38,322167.35,54762.0,100617.82
9396,3960,4261,2164653.27,206894.94,96473.0,177261.91

In [ ]:
import time 
start = time.time()
final_table = pd.read_sql("""
SELECT
    pp.VendorNumber,
    pp.VendorName,
    pp.Brand,
    pp.Price as ActualPrice,
    pp.Volume,
    pp.PurchasePrice,
    SUM(s.SalesQuantity) AS TotalSalesQuantity,
    SUM(s.SalesDollars) AS TotalSalesDollars,
    SUM(s.SalesPrice) AS TotalSalesPrice,
    SUM(s.ExciseTax) AS TotalExciseTax,
    SUM(vi.Quantity) AS TotalPurchaseQuantity,
    SUM(vi.Dollars) AS TotalPurchaseDollars,
    SUM(vi.Freight) AS TotalFreightCost
FROM purchase_prices pp
JOIN sales s
     ON pp.VendorNumber = s.VendorNo
     AND pp.Brand = s.Brand
JOIN vendor_invoice vi
     ON pp.VendorNumber = vi.VendorNumber
GROUP BY 
    pp.VendorNumber, 
    pp.Brand, 
    pp.Price, 
    pp.PurchasePrice
""", engine)

end = time.time()

In [ ]:
final_table

In [23]:
import pandas as pd
import time

start = time.time()

# 1️ purchase_prices 
pp = pd.read_sql("""
SELECT 
    VendorNumber,
    VendorName,
    Brand,
    Price AS ActualPrice,
    Volume,
    PurchasePrice
FROM purchase_prices
""", engine)


# 2️ sales aggregated
sales = pd.read_sql("""
SELECT 
    VendorNo,
    Brand,
    MAX(Description) AS Description,
    SUM(SalesQuantity) AS TotalSalesQuantity,
    SUM(SalesDollars) AS TotalSalesDollars,
    SUM(SalesPrice) AS TotalSalesPrice,
    SUM(ExciseTax) AS TotalExciseTax
FROM sales
GROUP BY VendorNo, Brand
""", engine)


# 3️ vendor_invoice aggregated
vi = pd.read_sql("""
SELECT 
    VendorNumber,
    SUM(Quantity) AS TotalPurchaseQuantity,
    SUM(Dollars) AS TotalPurchaseDollars,
    SUM(Freight) AS TotalFreightCost
FROM vendor_invoice
GROUP BY VendorNumber
""", engine)


#  Merge 1: purchase_prices + sales
df = pd.merge(
    pp,
    sales,
    left_on=["VendorNumber", "Brand"],
    right_on=["VendorNo", "Brand"],
    how="left"
)

# drop duplicate column
df.drop(columns=["VendorNo"], inplace=True)


#  Merge 2: above + vendor_invoice
final_table = pd.merge(
    df,
    vi,
    on="VendorNumber",
    how="left"
)


end = time.time()

print("Time taken:", end - start)

# Preview
print(final_table.head())

Time taken: 56.958336353302
   VendorNumber                   VendorName  Brand  ActualPrice Volume  \
0          8320  SHAW ROSS INT L IMP LTD         58        12.99    750
1          1128  BROWN-FORMAN CORP               62        36.99    750
2          1128  BROWN-FORMAN CORP               63        38.99    750
3          9165  ULTRA BEVERAGE COMPANY LLP      72        34.99    750
4          7245  PROXIMO SPIRITS INC.            75        14.99    750

   PurchasePrice                  Description  TotalSalesQuantity  \
0           9.28  Gekkeikan Black & Gold Sake              1589.0
1          28.67     Herradura Silver Tequila              1481.0
2          30.46   Herradura Reposado Tequila              1265.0
3          26.11         No. 3 London Dry Gin               252.0
4          10.94    Three Olives Tomato Vodka                19.0

   TotalSalesDollars  TotalSalesPrice  TotalExciseTax  TotalPurchaseQuantity  \
0           20641.11         13483.62         1252.08                69127.0
1           57232.19         43703.70         1167.38              1006122.0
2           51382.35         40468.03          997.42              1006122.0
3            9277.48          6103.33          198.71              1077527.0
4             284.81           119.92           14.96               682042.0

   TotalPurchaseDollars  TotalFreightCost
0             624979.64           3151.92
1           13529433.08          68601.68
2           13529433.08          68601.68
3           13210613.93          68054.70
4            7588029.90          38994.78

In [24]:
final_table

,VendorNumber,VendorName,Brand,ActualPrice,Volume,PurchasePrice,Description,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,TotalPurchaseQuantity,TotalPurchaseDollars,TotalFreightCost
0,8320,SHAW ROSS INT L IMP LTD,58,12.99,750,9.28,Gekkeikan Black & Gold Sake,1589.0,20641.11,13483.62,1252.08,69127.0,624979.64,3151.92
1,1128,BROWN-FORMAN CORP,62,36.99,750,28.67,Herradura Silver Tequila,1481.0,57232.19,43703.70,1167.38,1006122.0,13529433.08,68601.68
2,1128,BROWN-FORMAN CORP,63,38.99,750,30.46,Herradura Reposado Tequila,1265.0,51382.35,40468.03,997.42,1006122.0,13529433.08,68601.68
3,9165,ULTRA BEVERAGE COMPANY LLP,72,34.99,750,26.11,No. 3 London Dry Gin,252.0,9277.48,6103.33,198.71,1077527.0,13210613.93,68054.70
4,7245,PROXIMO SPIRITS INC.,75,14.99,750,10.94,Three Olives Tomato Vodka,19.0,284.81,119.92,14.96,682042.0,7588029.90,38994.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12256,90024,VINILANDIA USA,44917,24.99,750,16.55,NaN,NaN,NaN,NaN,NaN,59428.0,548855.37,2802.64
12257,4425,MARTIGNETTI COMPANIES,44944,22.99,750,14.93,NaN,NaN,NaN,NaN,NaN,2640411.0,27861690.02,144929.24
12258,10754,PERFECTA WINES,45016,93.99,750,61.43,NaN,NaN,NaN,NaN,NaN,553116.0,5665501.53,28720.52
12259,9744,FREDERICK WILDMAN & SONS,46011,12.99,1500,8.90,NaN,NaN,NaN,NaN,NaN,70932.0,759449.24,3999.93
12260,10754,PERFECTA WINES,46964,35.99,750,24.32,NaN,NaN,NaN,NaN,NaN,553116.0,5665501.53,28720.52

This Query generates a vendor-wise sales and purchases summary, which is valuable for:
Performance Optimization:
* The Query involves heavy joins and aggregations on large datasets like sales purchses.
* Storing the pre-aggregated results avoids repeated expensive computations.
* Helps in analyzing sales, purchases, and pricing for different vendors and brands.
* Furure Benefits of Storing this data for faster Dashborading & Reporting.
* Instead of running expensive quesries each time, dashboads can fetch data quickly from vendor_sales_summary

In [33]:
final_table.dtypes

VendorNumber               int64
VendorName                object
Brand                      int64
ActualPrice              float64
Volume                   float64
PurchasePrice            float64
Description               object
TotalSalesQuantity       float64
TotalSalesDollars        float64
TotalSalesPrice          float64
TotalExciseTax           float64
TotalPurchaseQuantity    float64
TotalPurchaseDollars     float64
TotalFreightCost         float64
dtype: object

In [37]:
final_table.isnull().sum()

VendorNumber             0
VendorName               0
Brand                    0
ActualPrice              0
Volume                   0
PurchasePrice            0
Description              0
TotalSalesQuantity       0
TotalSalesDollars        0
TotalSalesPrice          0
TotalExciseTax           0
TotalPurchaseQuantity    0
TotalPurchaseDollars     0
TotalFreightCost         0
dtype: int64

In [36]:
final_table['VendorName'].unique()

array(['SHAW ROSS INT L IMP LTD', 'BROWN-FORMAN CORP',
       'ULTRA BEVERAGE COMPANY LLP', 'PROXIMO SPIRITS INC.',
       'MOET HENNESSY USA INC', 'BACARDI USA INC',
       'JIM BEAM BRANDS COMPANY', 'CAMPARI AMERICA',
       'WILLIAM GRANT & SONS INC', 'MARTIGNETTI COMPANIES',
       'CONSTELLATION BRANDS INC', 'M S WALKER INC',
       'DIAGEO NORTH AMERICA INC', 'MCCORMICK DISTILLING CO',
       'PERNOD RICARD USA', 'PINE STATE TRADING CO',
       'STATE WINE & SPIRITS', 'DISARONNO INTERNATIONAL LLC',
       'SAZERAC CO INC', 'PERFECTA WINES', 'HEAVEN HILL DISTILLERIES',
       'LABELLE VYDS AND WINERY', 'REMY COINTREAU USA INC',
       'SIDNEY FRANK IMPORTING CO', 'MHW LTD', 'PHILLIPS PRODUCTS CO.',
       'LUXCO INC', 'WESTERN SPIRITS BEVERAGE CO', 'CASTLE BRANDS CORP.',
       'SAZERAC NORTH AMERICA INC.', 'OLE SMOKY DISTILLERY LLC',
       'STOLI GROUP,(USA) LLC', 'SMOKY QUARTZ DISTILLERY LLC',
       'VINEDREA WINES LLC', 'EDRINGTON AMERICAS',
       'DUGGANS DISTILLED PRODUCTS', 'PALM BAY INTERNATIONAL INC',
       'E & J GALLO WINERY', 'FLAG HILL WINERY & VINEYARD',
       'FREDERICK WILDMAN & SONS', 'BULLY BOY DISTILLERS',
       'DJINN SPIRITS LLC', 'THE PIERPONT GROUP LLC',
       'STAR INDUSTRIES INC.', 'TY KU LLC', 'Serralles Usa LLC',
       'SEA HAGG DISTILLERY LLC', 'WHYTE & MACKAY',
       'SOUTHERN WINE & SPIRITS NE', 'Mizkan Americas, Inc.',
       'Russian Standard Vodka', 'BLACK PRINCE DISTILLERY INC',
       'KLIN SPIRITS LLC', 'MARSALLE COMPANY',
       'CHARLES JACQUIN ET CIE INC', 'KOBRAND CORPORATION',
       'WINE GROUP INC', 'FABRIZIA SPIRITS LLC', 'LAIRD & CO',
       'AMERICAN VINTAGE BEVERAGE', 'NICHE W & S',
       'STE MICHELLE WINE ESTATES', 'BANFI PRODUCTS CORP',
       'TRINCHERO FAMILY ESTATES', 'DIAGEO CHATEAU ESTATE WINES',
       'MAJESTIC FINE WINES', 'TREASURY WINE ESTATES',
       'VINEYARD BRANDS INC', 'PREMIER DISTRIBUTORS',
       'PREMIUM PORT WINES, INC.', 'ALTAMAR BRANDS LLC',
       'TAKARA SAKE USA INC', 'DELICATO VINEYARDS INC', 'VINILANDIA USA',
       'THE IMPORTED GRAPE LLC', 'CANDIA VINEYARDS', 'CRUSH WINES',
       'LATITUDE BEVERAGE COMPANY', 'POVERTY LANE ORCHARDS',
       'MOONLIGHT MEADERY', 'SURVILLE ENTERPRISES CORP',
       'SWEET BABY VINEYARD', 'VINEXTRA INC', 'STELLAR IMPORTING CO LLC',
       'VRANKEN AMERICA', 'JEWELL TOWNE VINEYARDS',
       'HAUNTING WHISPER VYDS', 'ZORVINO VINEYARDS', 'R.P.IMPORTS INC',
       'PSP WINES', 'MILTONS DISTRIBUTING CO', 'SEA BREEZE CELLARS LLC',
       'SILVER MOUNTAIN CIDERS', 'FORTUNE WINE BROKERS LLC',
       'FANTASY FINE WINES CORP', 'PARK STREET IMPORTS LLC',
       'CAPSTONE INTERNATIONAL', 'CALEDONIA SPIRITS INC',
       'WEIN BAUER INC', 'INCREDIBREW INC', 'ADAMBA IMPORTS INTL INC',
       'Circa Wines', 'TALL SHIP DISTILLERY LLC', 'ALISA CARR BEVERAGES',
       'CENTEUR IMPORTS LLC', 'BLACK ROCK SPIRITS LLC', 'HALO DISTILLERY',
       'Dunn Wine Brokers', 'FULCHINO VINEYARD INC',
       'AMERICAN SPIRITS EXCHANGE', 'LAUREATE IMPORTS CO', 'UNCORKED',
       'HOOD RIVER DISTILLERS, Inc.', 'BERNIKO LLC',
       'IRA GOLDMAN AND WILLIAMS, LLP', 'BRONCO WINE COMPANY',
       'FLEMISH LION LLC', 'EXCLUSIVE WINES & SPIRITS',
       'MANGO BOTTLING INC', 'APPOLO VINEYARDS LLC',
       'WALPOLE MTN VIEW WINERY', 'ATLANTIC IMPORTING COMPANY',
       'HIGHLAND WINE MERCHANTS LLC', 'TAMWORTH DISTILLING',
       'SWEETWATER FARM', 'STARK BREWING COMPANY', 'TRUETT HURST',
       'SOUTHERN GLAZERS W&S OF NE', 'GILMANTON WINERY & VINEYARD',
       'AAPER ALCOHOL & CHEMICAL CO', 'BLACK COVE BEVERAGES',
       'LOYAL DOG WINERY', 'VINEYARD BRANDS LLC'], dtype=object)

In [28]:
final_table['Description'].unique()

array(['Gekkeikan Black & Gold Sake', 'Herradura Silver Tequila',
       'Herradura Reposado Tequila', ..., 'Frank Family Vyds Cab Svgn',
       'Feast Agiorgitiko', 'Feast Moschofilero'],
      shape=(8636,), dtype=object)

In [32]:
final_table['Volume'] = pd.to_numeric(
    final_table['Volume']
        .astype(str)
        .str.replace('[^0-9.]', '', regex=True),
    errors='coerce'
)

In [34]:
final_table.fillna(0, inplace = True)

In [35]:
final_table['VendorName'] = final_table['VendorName'].str.strip()

In [38]:
final_table

,VendorNumber,VendorName,Brand,ActualPrice,Volume,PurchasePrice,Description,TotalSalesQuantity,TotalSalesDollars,TotalSalesPrice,TotalExciseTax,TotalPurchaseQuantity,TotalPurchaseDollars,TotalFreightCost
0,8320,SHAW ROSS INT L IMP LTD,58,12.99,750.0,9.28,Gekkeikan Black & Gold Sake,1589.0,20641.11,13483.62,1252.08,69127.0,624979.64,3151.92
1,1128,BROWN-FORMAN CORP,62,36.99,750.0,28.67,Herradura Silver Tequila,1481.0,57232.19,43703.70,1167.38,1006122.0,13529433.08,68601.68
2,1128,BROWN-FORMAN CORP,63,38.99,750.0,30.46,Herradura Reposado Tequila,1265.0,51382.35,40468.03,997.42,1006122.0,13529433.08,68601.68
3,9165,ULTRA BEVERAGE COMPANY LLP,72,34.99,750.0,26.11,No. 3 London Dry Gin,252.0,9277.48,6103.33,198.71,1077527.0,13210613.93,68054.70
4,7245,PROXIMO SPIRITS INC.,75,14.99,750.0,10.94,Three Olives Tomato Vodka,19.0,284.81,119.92,14.96,682042.0,7588029.90,38994.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12256,90024,VINILANDIA USA,44917,24.99,750.0,16.55,0,0.0,0.00,0.00,0.00,59428.0,548855.37,2802.64
12257,4425,MARTIGNETTI COMPANIES,44944,22.99,750.0,14.93,0,0.0,0.00,0.00,0.00,2640411.0,27861690.02,144929.24
12258,10754,PERFECTA WINES,45016,93.99,750.0,61.43,0,0.0,0.00,0.00,0.00,553116.0,5665501.53,28720.52
12259,9744,FREDERICK WILDMAN & SONS,46011,12.99,1500.0,8.90,0,0.0,0.00,0.00,0.00,70932.0,759449.24,3999.93
12260,10754,PERFECTA WINES,46964,35.99,750.0,24.32,0,0.0,0.00,0.00,0.00,553116.0,5665501.53,28720.52

In [40]:
final_table['GrossProfit'] = final_table['TotalSalesDollars'] - final_table['TotalPurchaseDollars']

In [41]:
final_table['GrossProfit'].min()

np.float64(-50959796.849999994)

In [42]:
final_table['GrossProfit']

0         -604338.53
1       -13472200.89
2       -13478050.73
3       -13201336.45
4        -7587745.09
            ...
12256     -548855.37
12257   -27861690.02
12258    -5665501.53
12259     -759449.24
12260    -5665501.53
Name: GrossProfit, Length: 12261, dtype: float64

In [43]:
final_table['ProfitMargin'] = (final_table['GrossProfit'] / final_table['TotalSalesDollars'])*100

In [44]:
final_table['ProfitMargin']

0       -2.927839e+03
1       -2.353955e+04
2       -2.623090e+04
3       -1.422944e+05
4       -2.664143e+06
             ...
12256            -inf
12257            -inf
12258            -inf
12259            -inf
12260            -inf
Name: ProfitMargin, Length: 12261, dtype: float64

In [45]:
final_table['StockTurnover'] =  final_table['TotalSalesQuantity'] /   final_table['TotalPurchaseQuantity']

In [46]:
final_table['StockTurnover']

0        0.022987
1        0.001472
2        0.001257
3        0.000234
4        0.000028
           ...
12256    0.000000
12257    0.000000
12258    0.000000
12259    0.000000
12260    0.000000
Name: StockTurnover, Length: 12261, dtype: float64

In [47]:
final_table['SalesToPucharseRatio'] = final_table['TotalSalesDollars'] / final_table['TotalPurchaseDollars']

In [48]:
final_table['SalesToPucharseRatio']

0        0.033027
1        0.004230
2        0.003798
3        0.000702
4        0.000038
           ...
12256    0.000000
12257    0.000000
12258    0.000000
12259    0.000000
12260    0.000000
Name: SalesToPucharseRatio, Length: 12261, dtype: float64

In [59]:
conn = engine.raw_connection()
cursor = conn.cursor()

In [56]:
final_table.columns

Index(['VendorNumber', 'VendorName', 'Brand', 'ActualPrice', 'Volume',
       'PurchasePrice', 'Description', 'TotalSalesQuantity',
       'TotalSalesDollars', 'TotalSalesPrice', 'TotalExciseTax',
       'TotalPurchaseQuantity', 'TotalPurchaseDollars', 'TotalFreightCost',
       'GrossProfit', 'ProfitMargin', 'StockTurnover', 'SalesToPucharseRatio'],
      dtype='object')

In [64]:
cursor.execute("""CREATE TABLE vendor_sales_summary (
    VendorNumber INT,
    VendorName VARCHAR(100),
    Brand INT,
    ActualPrice DECIMAL(10, 2),
    Volume FLOAT,
    PurchasePrice DECIMAL(10,2),
    Description VARCHAR(100),
    TotalSalesQuantity INT,
    TotalSalesDollars DECIMAL(15,2),
    TotalSalesPrice DECIMAL(15,2),
    TotalExciseTax DECIMAL(15,2),
    TotalPurchaseQuantity INT,
    TotalPurchaseDollars DECIMAL(15,2),
    TotalFreightCost DECIMAL(15,2),
    GrossProfit DECIMAL(15,2),
    ProfitMargin DECIMAL(15,2),
    StockTurnover DECIMAL(15,2),
    SalesToPucharseRatio DECIMAL(15,2),
    PRIMARY KEY (VendorNumber, Brand)
);

""")

OperationalError: (1050, "Table 'vendor_sales_summary' already exists")

In [65]:
pd.read_sql("Select * from vendor_sales_summary", engine)

Empty DataFrame
Columns: [VendorNumber, VendorName, Brand, ActualPrice, Volume, PurchasePrice, Description, TotalSalesQuantity, TotalSalesDollars, TotalSalesPrice, TotalExciseTax, TotalPurchaseQuantity, TotalPurchaseDollars, TotalFreightCost, GrossProfit, ProfitMargin, StockTurnover, SalesToPucharseRatio]
Index: []

In [69]:
final_table.to_sql(
    "vendor_sales_summary",
    con=engine,
    if_exists='append',   
    index=False,
    chunksize=1000     
)

ValueError: inf cannot be used with MySQL

In [70]:
import numpy as np

final_table.replace([np.inf, -np.inf], np.nan, inplace=True)

In [71]:
final_table = final_table.where(pd.notnull(final_table), None)

In [72]:
final_table.fillna(0, inplace=True)

In [73]:
final_table.to_sql(
    "vendor_sales_summary",
    con=engine,
    if_exists='append',
    index=False,
    chunksize=1000
)

12261

NameError: name 'vendor_sales_summary' is not defined